### ISSUE TITLE
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

### ISSUE THREAD

**Issue by MengWangTHU** [Vegeta2020/SE-SSD#37]
Traing kitti data, when i modify the config file from single car-task to all classes(car\pedestrian\cyclist)task, error occures.
The information is here:

> Traceback (most recent call last):
  File "train.py", line 118, in <module>
    main()
  File "train.py", line 115, in main
    train_detector(model, datasets, cfg, distributed=distributed, validate=args.validate, logger=logger,)
  File "/home/l4/wangmeng/SE-SSD/det3d/torchie/apis/train_sessd.py", line 321, in train_detector
    trainer.load_checkpoint_from_scratch(cfg.load_from)
  File "/home/l4/wangmeng/SE-SSD/det3d/torchie/trainer/trainer_sessd.py", line 216, in load_checkpoint_from_scratch
    self.optimizer.load_state_dict(checkpoint_0["optimizer"])
  File "/home/l4/anaconda3/envs/SE-SSD/lib/python3.7/site-packages/torch/optim/optimizer.py", line 123, in load_state_dict
    raise ValueError("loaded state dict contains a parameter group "
ValueError: loaded state dict contains a parameter group that doesn't match the size of optimizer's group

Dose anyone know the problem?

**Comment by Vegeta2020** [comment]
@MengWangTHU We have not train all classes before.... your bug seems show the loaded checkpoint mismatch with your network structure.
