### ISSUE TITLE
ValueError: need at least one array to concatenate

### ISSUE THREAD

**Issue by pervaizniazi** [Vegeta2020/SE-SSD#45]
Hi,

I am getting following error:

  File "train.py", line 128, in <module>
    main()
  File "train.py", line 125, in main
    train_detector(model, datasets, cfg, distributed=distributed, validate=args.validate, logger=logger,)
  File "/Code/SE-SSD/det3d/torchie/apis/train_sessd.py", line 328, in train_detector
    trainer.run(data_loaders, cfg.workflow, cfg.total_epochs, local_rank=cfg.local_rank)
  File "/Code/SE-SSD/det3d/torchie/trainer/trainer_sessd.py", line 472, in run
    epoch_runner(data_loaders[0], data_loaders[1], self.epoch, **kwargs)
  File "/Code/SE-SSD/det3d/torchie/trainer/trainer_sessd.py", line 333, in train
    for i, data_batch in enumerate(data_loader):
  File "/miniconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
    data = self._next_data()
  File "/miniconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
    return self._process_data(data)
  File "/miniconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
    data.reraise()
  File "/miniconda3/envs/py36/lib/python3.6/site-packages/torch/_utils.py", line 394, in reraise
    raise self.exc_type(msg)
ValueError: Caught ValueError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/miniconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/miniconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/miniconda3/envs/py36/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/Code/SE-SSD/det3d/datasets/kitti/kitti.py", line 170, in __getitem__
    return self.get_sensor_data(idx, with_gp=False)
  File "/Code/SE-SSD/det3d/datasets/kitti/kitti.py", line 209, in get_sensor_data
    data, _ = self.pipeline(res, info)
  File "/Code/SE-SSD/det3d/datasets/pipelines/compose.py", line 23, in __call__
    res, info = t(res, info)
  File "/Code/SE-SSD/det3d/datasets/pipelines/preprocess.py", line 93, in __call__
    targeted_class_names=self.class_names,
  File "/Code/SE-SSD/det3d/core/sampler/sample_ops_v2.py", line 187, in sample_all
    "points": np.concatenate(s_points_list, axis=0),
  File "<__array_function__ internals>", line 6, in concatenate
ValueError: need at least one array to concatenate

I think the problem is with data loading, but not sure how to fix it. I have verified the dataset paths, and configuration file also looks good.
Any hint/suggestion will be appreciated.

Thanks,
Pervaiz Khan.

**Comment by bingo830422** [comment]
check `config.py`

```
dict(filter_by_difficulty=[-1],),    # todo: need to check carefully
```

You could modify to not filtering anything by difficulty.
Just remove elements in list, such as:
```
dict(filter_by_difficulty=[],),    # todo: need to check carefully
```
