### ISSUE TITLE
 KeyError: 'transformation'

### ISSUE THREAD

**Issue by YanXiaoYY** [Vegeta2020/SE-SSD#67]
Traceback (most recent call last):
  File "train.py", line 119, in <module>
    main()
  File "train.py", line 116, in main
    train_detector(model, datasets, cfg, distributed=distributed, validate=args.validate, logger=logger,)
  File "/home/wy/SE-SSD/det3d/torchie/apis/train_sessd.py", line 326, in train_detector
    trainer.run(data_loaders, cfg.workflow, cfg.total_epochs, local_rank=cfg.local_rank)
  File "/home/wy/SE-SSD/det3d/torchie/trainer/trainer_sessd.py", line 472, in run
    epoch_runner(data_loaders[0], data_loaders[1], self.epoch, **kwargs)
  File "/home/wy/SE-SSD/det3d/torchie/trainer/trainer_sessd.py", line 346, in train
    outputs = self.batch_processor_inline(self.model, self.model_ema, data_batch, consistency_weight, train_mode=True, **kwargs)
  File "/home/wy/SE-SSD/det3d/torchie/trainer/trainer_sessd.py", line 266, in batch_processor_inline
    losses = model(example, is_ema=[False, output_ema], return_loss=True)
  File "/home/wy/SE-SSD/venv/lib/python3.6/site-packages/torch/nn/modules/module.py", line 541, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/wy/SE-SSD/det3d/models/detectors/voxelnet_sessd.py", line 42, in forward
    return self.bbox_head.loss(example, preds, is_ema[1])
  File "/home/wy/SE-SSD/det3d/models/bbox_heads/mg_head_sessd.py", line 709, in loss
    consistency_loss = self.consistency_loss(preds_dicts, preds_ema, example)
  File "/home/wy/SE-SSD/det3d/models/bbox_heads/mg_head_sessd.py", line 628, in consistency_loss
    batch_trans = example['transformation']
KeyError: 'transformation'

Is there a lack of record of data enhancement? Did you use the key?

**Comment by YanXiaoYY** [comment]
I have solved this problem. I downloaded the code again and replace det3d file
