### ISSUE TITLE
The following error occurred when I compiled and installed iou3d

### ISSUE THREAD

**Issue by libingDY** [Vegeta2020/SE-SSD#76]
g++: error: /home/libing/newstorage/3Dobjectdetector/SE-SSD/det3d/core/iou3d/build/temp.linux-x86_64-3.7/src/iou3d.o: 没有那个文件或目录
g++: error: /home/libing/newstorage/3Dobjectdetector/SE-SSD/det3d/core/iou3d/build/temp.linux-x86_64-3.7/src/iou3d_kernel.o: 没有那个文件或目录
g++: error: /home/libing/newstorage/3Dobjectdetector/SE-SSD/det3d/core/iou3d/build/temp.linux-x86_64-3.7/src/iou3d_cpu.o: 没有那个文件或目录
error: command 'g++' failed with exit status 1

I can't compile those three files

My environment is：
cuda 10.1
pytorch 1.7

I can't compile the following three files

What is the configuration of your environment？

**Comment by Vegeta2020** [comment]
@libingDY You may find the env config in https://github.com/poodarchu/Det3D/blob/master/INSTALLATION.md

For my env,  the cuda 10.1 and pytorch 1.4.0 is fine, but  I have not used so high version of pytorch as 1.7.

**Comment by libingDY** [comment]
Thank you very much for your reply. I have changed the version of torch, but I have encountered the following problems：


True
Traceback (most recent call last):
  File "train.py", line 18, in <module>
    from det3d.torchie.apis import (
  File "/home/libing/newstorage/3Dobjectdetector/SE-SSD/det3d/torchie/apis/__init__.py", line 5, in <module>
    from .train_sessd import batch_processor, build_optimizer, train_detector
  File "/home/libing/newstorage/3Dobjectdetector/SE-SSD/det3d/torchie/apis/train_sessd.py", line 7, in <module>
    import apex
  File "/home/libing/anaconda3/envs/HVPR/lib/python3.7/site-packages/apex/__init__.py", line 23, in <module>
    from . import transformer
  File "/home/libing/anaconda3/envs/HVPR/lib/python3.7/site-packages/apex/transformer/__init__.py", line 1, in <module>
    from apex.transformer import amp
  File "/home/libing/anaconda3/envs/HVPR/lib/python3.7/site-packages/apex/transformer/amp/__init__.py", line 1, in <module>
    from apex.transformer.amp.grad_scaler import GradScaler
  File "/home/libing/anaconda3/envs/HVPR/lib/python3.7/site-packages/apex/transformer/amp/grad_scaler.py", line 8, in <module>
    class GradScaler(torch.cuda.amp.GradScaler):
AttributeError: module 'torch.cuda' has no attribute 'amp'

**Comment by Vegeta2020** [comment]
@libingDY It seems an issue of apex, you may also need to reinstall it after updating your pytorch version.

**Comment by LiuPearl1** [comment]
@Vegeta2020 My environment is the cuda 10.1 and pytorch 1.4.0, And I meet "AttributeError: module 'torch.cuda' has no attribute 'amp'" problem, should I update my torch version? But high version torch will meet build problem like #22 . So which version is right?

**Comment by 346575116** [comment]
> 

请问这个问题解决了吗？我也遇到了同样的问题，我的环境是cuda10.0和pytorch1.1.0，尝试升级pytorch1.7也会带来其他问题。

**Comment by qq123aa456** [comment]
@LiuPearl1  have you solved it?I meet the same question which puzzled me long time.
