### ISSUE TITLE
The problem about run train.py

### ISSUE THREAD

**Issue by LuYujing-97** [Vegeta2020/SE-SSD#88]
Hello, when I run train.py, I meet this problem, do you know how to solve it?
$ python train.py                                                                                                                   
True                                                                                                                                                                        
Traceback (most recent call last):                                                                                                                                          
  File "train.py", line 15, in <module>                                                                                                                                     
    from det3d.datasets import build_dataset                                                                                                                                
  File "/home/zjlab/lyj/SE-SSD/det3d/datasets/__init__.py", line 4, in <module>                                                                                             
    from .kitti import KittiDataset                                                                                                                                         
  File "/home/zjlab/lyj/SE-SSD/det3d/datasets/kitti/__init__.py", line 1, in <module>                                                                                       
    from .kitti import KittiDataset                                                                                                                                         
  File "/home/zjlab/lyj/SE-SSD/det3d/datasets/kitti/kitti.py", line 10, in <module>                                                                                         
    from det3d.datasets.custom import PointCloudDataset                                                                                                                     
  File "/home/zjlab/lyj/SE-SSD/det3d/datasets/custom.py", line 8, in <module>                                                                                               
    from .pipelines import Compose                                                                                                                                          
  File "/home/zjlab/lyj/SE-SSD/det3d/datasets/pipelines/__init__.py", line 20, in <module>                                                                                  
    from .preprocess import Preprocess, Voxelization, AssignTarget                                                                                                          
  File "/home/zjlab/lyj/SE-SSD/det3d/datasets/pipelines/preprocess.py", line 9, in <module>                                                                                 
    from det3d.builder import (                                                                                                                                             
  File "/home/zjlab/lyj/SE-SSD/det3d/builder.py", line 18, in <module>                                                                                                      
    from det3d.models.losses import GHMCLoss, GHMRLoss, losses                                                                                                              
  File "/home/zjlab/lyj/SE-SSD/det3d/models/__init__.py", line 2, in <module>                                                                                               
    from .backbones import *  # noqa: F401,F403                                                                                                                             
  File "/home/zjlab/lyj/SE-SSD/det3d/models/backbones/__init__.py", line 3, in <module>                                                                                     
    from .scn import SpMiddleFHD                                                                                                                                            
  File "/home/zjlab/lyj/SE-SSD/det3d/models/backbones/scn.py", line 6, in <module>                                                                                          
    from det3d.models.utils import Empty, change_default_args                                                                                                               
  File "/home/zjlab/lyj/SE-SSD/det3d/models/utils/__init__.py", line 1, in <module>                                                                                         
    from .conv_module import ConvModule, build_conv_layer                                                                                                                   
  File "/home/zjlab/lyj/SE-SSD/det3d/models/utils/conv_module.py", line 7, in <module>                                                                                      
    from .norm import build_norm_layer                                                                                                                                      
  File "/home/zjlab/lyj/SE-SSD/det3d/models/utils/norm.py", line 4, in <module>                                                                                             
    from det3d.ops.syncbn import DistributedSyncBN                                                                                                                          
  File "/home/zjlab/lyj/SE-SSD/det3d/ops/syncbn/__init__.py", line 1, in <module>                                                                                           
    from .syncbn import DistributedSyncBN                                                                                                                                   
  File "/home/zjlab/lyj/SE-SSD/det3d/ops/syncbn/syncbn.py", line 12, in <module>                                                                                            
    from . import syncbn_gpu                                                                                                                                                
ImportError: /home/zjlab/lyj/SE-SSD/det3d/ops/syncbn/syncbn_gpu.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN6caffe26detail36_typeMetaDataInstance_preallocated_7E

**Comment by Vegeta2020** [comment]
@LuYujing-97 Try to re-install the module SE-SSD/det3d/ops/syncbn.
